### ISSUE TITLE
Is sort on the roadmap?

### ISSUE THREAD

**Issue by mclarsen** [LLNL/RAJA#473] opened 2018-05-07 20:11 UTC
I was just wondering if a sort operation is on the RAJA roadmap? It would be nice to take advantage of cuda's radix sort for my work.

**Comment by rhornung67** [comment] 2018-05-07 20:54
@mclarsen we've talked about putting together a library of utility routines to accompany RAJA at some point, but haven't done anything about it yet. We would probably base what we do on the CUB library https://github.com/NVlabs/cub

**Comment by mclarsen** [comment] 2018-05-08 03:57
@rhornung67 That would be something I would be interested in. I just wanted to keep this on your radar. I am just wading into the RAJA waters, and for now, I am just going to implement a sort or use std::sort to get myself bootstrapped.

**Comment by gzagaris** [comment] 2019-09-06 17:33
I recently run into problems using CUB's sorting routines. I am not 100% clear whether the problem is with the device linker or a "fix" in CUB is more appropriate. Looking a bit further for other alternatives, I came across this library: https://moderngpu.github.io/mergesort.html

It would be nice to encapsulate parallel sort primitives in RAJA.

**Comment by rhornung67** [comment] 2020-07-15 21:41
@mclarsen and @gzagaris a variety of sorts will be available in the next RAJA release coming out early-mid August. Here's a preview: https://raja.readthedocs.io/en/feature-burmark1-sort/feature/sort.html

**Comment by gzagaris** [comment] 2020-07-15 21:43
Thanks @rhornung67  -- That's great! I look forward to take it for a spin in Axom.

**Comment by MrBurmark** [comment] 2021-05-17 18:03
Can we close this now that RAJA has sort?

**Comment by rhornung67** [comment] 2021-05-17 18:40
Definitely. You can have the honor.

**Closed** 2022-01-06 22:08 UTC
