### ISSUE TITLE
Build fails with CUDA v8.0

### ISSUE THREAD

**Issue by xing-liu** [LLNL/RAJA#122] opened 2016-09-01 18:47 UTC
I tried to build RAJA on a POWER8 system, but it failed with the following error messages.

[ 15%] Built target lulesh-OMP.exe
[ 16%] Building NVCC (Device) object test/LULESH-v1.0/LULESH-v1.0_RAJA-variants/CMakeFiles/lulesh-RAJA-parallel.exe.dir/lulesh-RAJA-parallel.exe_generated_luleshRAJA-parallel.cxx.o
/home/mstars/RAJA-develop/include/RAJA/exec-cuda/reduce_cuda.hxx(269): error: cannot overload functions distinguished by return type alone

1 error detected in the compilation of "/tmp/tmpxft_0000fe77_00000000-5_luleshRAJA-parallel.cpp4.ii".
CMake Error at lulesh-RAJA-parallel.exe_generated_luleshRAJA-parallel.cxx.o.cmake:260 (message):
  Error generating file
/home/mstars/RAJA-develop/build/test/LULESH-v1.0/LULESH-v1.0_RAJA-variants/CMakeFiles/lulesh-RAJA-parallel.exe.dir//./lulesh-RAJA-parallel.exe_generated_luleshRAJA-parallel.cxx.o

make[2]: *** [test/LULESH-v1.0/LULESH-v1.0_RAJA-variants/CMakeFiles/lulesh-RAJA-parallel.exe.dir/lulesh-RAJA-parallel.exe_generated_luleshRAJA-parallel.cxx.o] Error 1
make[1]: *** [test/LULESH-v1.0/LULESH-v1.0_RAJA-variants/CMakeFiles/lulesh-RAJA-parallel.exe.dir/all] Error 2
make: *** [all] Error 2

**Comment by DavidPoliakoff** [comment] 2016-09-01 19:01
Hi Xing,

Thanks for the bug report. I wasn't able to reproduce this using just nvcc and CUDA8.0. Could you point me at the commit of RAJA you were using and the version of LULESH? Currently building RAJA doesn't build LULESH, so I'm having a little difficulty reproducing the bug.

**Comment by xing-liu** [comment] 2016-09-01 19:12
Hi David,

Thanks for the reply. I used the RAJA develop branch and checked out it around one month ago. Which version did you try? Does that version support RAJA::Tile?  

Xing

**Comment by DavidPoliakoff** [comment] 2016-09-01 19:14
Hi Xing,

If you're using the forallN constructs (are you part of the VBL effort?), I'm actually not entirely familiar with that segment of the code, so I'll see whether @ajkunen or @trws are able to chime in. Sorry I can't be of more help on that front.

Best,

David

**Comment by ajkunen** [comment] 2016-09-01 19:16
Hey Xing,

The Tile policy only works with forallN, not forall…. and I don’t believe that LULESH uses any forallN’s.

-Adam

**Comment by rhornung67** [comment] 2016-09-01 19:19
Correct. LULESH uses no forallN traversals. They are used in Kripke.  —Rich

**Comment by DavidPoliakoff** [comment] 2016-09-01 19:32
Xing,

It might be valuable for us to hear what you're trying to achieve so we can steer you towards making that happen. There's a known shortcoming of documentation for RAJA, currently an unfortunate amount of it is "raise an issue on Github and talk to the devs." If you tell us what you're trying to achieve (compiling code that was given to you and getting errors? Trying to optimize code and seeing a construct you thought would work not work?) we could try to get you going.

**Comment by xing-liu** [comment] 2016-09-02 00:04
David,

I'm helping LLNL to prepare an application for Sierra, which is using RAJA for GPU parallization. I talked to Jeff on the phone, and he asked me to create an issue on git if I have any questions about RAJA.

Xing

Xing

**Comment by trws** [comment] 2016-09-02 15:33
Right, and we're happy to help, but we need to know what the question is @xing-liu.  I'm pretty sure the compile error you're seeing will be fixed by PR #91, it has to do with the addition of double-precision atomics to the CUDA API in 8.0.  For the time being, you should either build with 7.5 or try a branch incorporating the fixes in #91.

All current branches (everything but example or reproducer branches I think) should support Tile for the ForallN constructs.

**Comment by rhornung67** [comment] 2016-09-30 22:07
@xing-liu or @trws or @DavidPoliakoff is this issue resolved?

**Comment by davidbeckingsale** [comment] 2016-10-27 18:31
I'm closing this since we don't have any information about the actual bug. Please re-open with more details if necessary.

**Closed by davidbeckingsale** 2016-10-27 18:31 UTC
