### ISSUE TITLE
Raja0.7.0 Warning

### ISSUE THREAD

**Issue by Ram3sh** [LLNL/RAJA#570] opened 2019-01-24 22:22 UTC
I get the warning:

/autofs/nccs-svm1_home1/rameshp/RAJA/RAJA-0.7.0/install/include/RAJA/config.hpp(345): warning: expression has no effect

for every file compiled. The line in question is the commented FIXME line below:

// FIXME: alignx is breaking CUDA+xlc
#if defined(RAJA_ENABLE_CUDA)
#define RAJA_ALIGN_DATA(d) d
#else
#define RAJA_ALIGN_DATA(d) __alignx(RAJA::DATA_ALIGN, d)
#endif

This is nvcc with xlC as host compiler on Summit. Happens on Lassen as well.

**Comment by rhornung67** [comment] 2019-08-29 17:49
Grfff!  @artv3 or @rchen20 can one of you please take a look at these warnings and see if you can quiet them. The first two should be easy. Not sure about the other two.  Thanks.

**Comment by rchen20** [comment] 2019-08-29 21:05
I can take a look at this.

**Comment by rchen20** [comment] 2019-09-20 19:50
@Ram3sh I built the latest RAJA 0.9.0 dev with cuda/10.1.234 + xl/2019.08.20, and cuda/10.1.168 + xl/2019.06.12 on LASSEN and could not reproduce either of those warnings. Same on RZANSEL. Are there particular NVCC and XL versions you are using? Thanks!

**Comment by Ram3sh** [comment] 2019-09-20 20:05
@rchen20 I am using gcc4.9.3:
cmake -DCMAKE_INSTALL_PREFIX=../install_warn -DENABLE_CUDA=On -DENABLE_OPENMP=Off ../
make
.....
Scanning dependencies of target test-atomic-ref-auto.exe
[  7%] Building CUDA object test/unit/CMakeFiles/test-atomic-ref-auto.exe.dir/test-atomic-ref-auto.cpp.o
/usr/workspace/wsrzd/ramesh/RAJA/RAJA-v0.9.0/include/RAJA/pattern/detail/reduce.hpp(104): warning: constexpr non-static member function will not be implicitly 'const' in C++14

/usr/workspace/wsrzd/ramesh/RAJA/RAJA-v0.9.0/include/RAJA/pattern/detail/reduce.hpp(110): warning: constexpr non-static member function will not be implicitly 'const' in C++14

/usr/workspace/wsrzd/ramesh/RAJA/RAJA-v0.9.0/include/RAJA/pattern/detail/reduce.hpp(123): warning: __host__ annotation is ignored on a function("operator=") that is explicitly defaulted on its first declaration

/usr/workspace/wsrzd/ramesh/RAJA/RAJA-v0.9.0/include/RAJA/pattern/detail/reduce.hpp(123): warning: __device__ annotation is ignored on a function("operator=") that is explicitly defaulted on its first declaration

/usr/workspace/wsrzd/ramesh/RAJA/RAJA-v0.9.0/include/RAJA/pattern/detail/reduce.hpp(104): warning: constexpr non-static member function will not be implicitly 'const' in C++14

/usr/workspace/wsrzd/ramesh/RAJA/RAJA-v0.9.0/include/RAJA/pattern/detail/reduce.hpp(110): warning: constexpr non-static member function will not be implicitly 'const' in C++14

/usr/workspace/wsrzd/ramesh/RAJA/RAJA-v0.9.0/include/RAJA/pattern/detail/reduce.hpp(123): warning: __host__ annotation is ignored on a function("operator=") that is explicitly defaulted on its first declaration

/usr/workspace/wsrzd/ramesh/RAJA/RAJA-v0.9.0/include/RAJA/pattern/detail/reduce.hpp(123): warning: __device__ annotation is ignored on a function("operator=") that is explicitly defaulted on its first declaration

[  7%] Linking CUDA device code CMakeFiles/test-atomic-ref-auto.exe.dir/cmake_device_link.o
[  8%] Linking CXX executable ../test-atomic-ref-auto.exe
[  8%] Built target test-atomic-ref-auto.exe

**Comment by rchen20** [comment] 2019-09-20 20:38
@Ram3sh Hmmm . . . I tried gcc4.9.3 on LASSEN and still could not reproduce those warnings. Does your RAJA/include/RAJA/pattern/detail/reduce.hpp:104 look like this?

  RAJA_HOST_DEVICE constexpr T value() const { return T(); }

https://github.com/LLNL/RAJA/blob/744f5275992bb5f73b97aa4262e6c2d65d90f83b/include/RAJA/pattern/detail/reduce.hpp#L104

If not, you may need to do a "git pull origin develop" to update.

Other than that, I am compiling with the RAJA build script: RAJA/scripts/lc-builds/blueos_nvcc10_gcc7.3.1.sh (except with gcc4.9.3 paths, and -DENABLE_OPENMP=Off like you are doing). The script has more CMAKE input, but those should not be generating those C++14 warnings.

**Comment by Ram3sh** [comment] 2019-09-20 20:47
@rchen20 I am using the last released version 0.9.0.

Line 104 is:
RAJA_HOST_DEVICE constexpr T value() { return T(); }

**Comment by rchen20** [comment] 2019-09-20 20:56
@Ram3sh I see, you are using the "master" 0.9.0 branch, which will certainly exhibit these warnings. The "develop" 0.9.0 branch has these warnings fixed.

You can just replace your RAJA/include/RAJA/pattern/detail/reduce.hpp with the version from "develop" 0.9.0. The only differences are the fixes for these warnings.

**Comment by rhornung67** [comment] 2020-05-06 22:30
@rchen20 If this is resolved, please close this issue.

**Closed** 2020-05-07 00:56 UTC
